name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          environment-file: environment.yml
          activate-environment: omics_cancer

      - name: Run tests
        run: |
          pytest -q
